export const TABLE = {
  PARTNERS:      'partners',
  TRANSACTIONS:  'transactions',
  PNL_REPORTS:   'pnl_reports',
  PNL_MONTHLY:   'pnl_monthly',
  SECURITIES:    'securities',
  ALLOCATIONS:   'allocations',
  LEADS:         'leads',
  STRATEGIES:    'strategies',
  AUDIT_LOG:     'audit_log',
  ARTICLES:      'articles',
  NOTIFICATIONS: 'notifications',
  ADMIN_ROLES:   'admin_roles',
  PAGE_EVENTS:   'page_events',
  QUARTERLY_RATES: 'quarterly_rates',
  APP_SETTINGS: 'app_settings',
  APPLY_TOKENS: 'apply_tokens',
} as const
