import { COMPANY_EMAIL, COMPANY_NAME } from './constants'

export const CONTENT = {
  login: {
    eyebrow: 'Partner Portal',
    heading: 'Welcome back.',
    subheading: 'Sign in to access your partner dashboard.',
    emailPlaceholder: 'Email address',
    passwordPlaceholder: 'Password',
    forgotPassword: 'Forgot password? →',
    signIn: 'Sign in →',
    notPartner: 'Not a partner yet? Start a conversation →',
    securityNote: 'Secure access. All data is encrypted and protected with bank-grade security.',
    signingIn: 'Signing in…',
  },

  nav: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    pnl: 'P&L',
    securities: 'Securities',
    profile: 'Profile',
    logout: 'Logout',
    partner: 'Partner',
  },

  dashboard: {
    greeting: {
      morning: 'Good morning',
      afternoon: 'Good afternoon',
      evening: 'Good evening',
    },
    subtitle: "Here's your portfolio overview.",
    metrics: {
      totalInvested: 'TOTAL INVESTED',
      totalInvestedSub: 'Across all markets',
      currentPnl: 'CURRENT P&L',
      distribution: "THIS QUARTER'S DISTRIBUTION",
      nextPayout: 'NEXT PAYOUT DATE',
      daysPrefix: 'In',
      daysSuffix: 'days',
    },
    chart: {
      title: 'Quarterly Performance',
      yearLabel: 'This Year',
      legend: 'Profit (Rs.)',
      bestMonth: 'Best Month',
      worstMonth: 'Worst Month',
      avgMonthly: 'Avg Monthly P&L',
      positiveMonths: 'Positive Months',
    },
    activity: {
      title: 'Recent Activity',
      viewAll: 'View all transactions →',
    },
    trust: {
      agreement: 'Your capital is protected by a signed Capital Partnership Agreement.',
      disclaimer: 'All performance is market-linked. No fixed or guaranteed returns.',
      viewAgreement: 'View Agreement →',
    },
  },

  transactions: {
    title: 'Transactions',
    totalInvested: 'Total Invested',
    totalDistributed: 'Total Distributed',
    netPnl: 'Net P&L',
    exportCsv: 'Export CSV',
    allTypes: 'All Types',
    showing: 'Showing',
    to: 'to',
    of: 'of',
    transactionsLabel: 'transactions',
    columns: {
      date: 'DATE',
      type: 'TYPE',
      amount: 'AMOUNT',
      status: 'STATUS',
      notes: 'NOTES',
    },
  },

  pnl: {
    title: 'P&L Report',
    totalPnl: 'Total P&L',
    realizedPnl: 'Realized P&L',
    unrealizedPnl: 'Unrealized P&L',
    winRate: 'Win Rate',
    cumulative: 'Cumulative',
    monthly: 'Monthly',
    chartTitle: 'Cumulative P&L Trend',
    monthlyBreakdown: 'Monthly P&L Breakdown',
    allStrategies: 'All Strategies',
    strategyPerformance: 'Strategy Performance',
    allocationTitle: 'Asset Allocation',
    totalLabel: 'Total',
  },

  securities: {
    title: 'Securities & Documents',
    agreementTitle: 'Capital Partnership Agreement',
    agreementMou: 'MoU Reference',
    agreementSigned: 'Signed',
    agreementPartner: 'Partner',
    downloadPdf: 'Download Agreement PDF',
    documentPending: `Document will be available once uploaded by admin. Contact ${COMPANY_EMAIL}`,
    securityTitle: 'Security / Collateral Details',
    chequeAmount: 'Cheque Amount',
    chequeDate: 'Cheque Date',
    chequeRef: 'Reference',
    viewDetails: 'View Details',
    historyTitle: 'Document History',
    columns: {
      document: 'DOCUMENT',
      date: 'DATE',
      type: 'TYPE',
      download: 'DOWNLOAD',
    },
  },

  profile: {
    title: 'Profile',
    name: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    tier: 'Tier',
    entryDate: 'Entry Date',
    status: 'Status',
    editButton: 'Edit Profile',
    editNote: `To update your details, contact ${COMPANY_EMAIL}`,
  },

  pending: {
    heading: 'Account setup in progress.',
    body: `Your partner account is being configured. Please contact ${COMPANY_EMAIL} if you need assistance.`,
    logout: 'Sign out',
  },

  errors: {
    generic: 'Something went wrong. Please try again.',
    authFailed: 'Invalid email or password.',
    notFound: 'Record not found.',
    retry: 'Retry',
  },

  admin: {
    nav: {
      overview:      'Overview',
      partners:      'Partners',
      pipeline:      'Pipeline',
      financials:    'Financials',
      distributions: 'Distributions',
      pnlEntry:      'P&L Entry',
      strategies:    'Strategies',
      allocation:    'Allocation',
      users:         'Users',
      documents:     'Documents',
      content:       'Content',
      notifications: 'Notifications',
      team:          'Team',
      system:        'System',
    },
    sections: {
      operations: 'OPERATIONS',
      finance:    'FINANCE',
      content:    'CONTENT',
      system:     'SYSTEM',
    },
    badge: 'Admin',
    overview: {
      title:           'Overview',
      aum:             'Total AUM',
      activePartners:  'Active Partners',
      distributions:   'Q Distributions',
      nextPayout:      'Next Payout',
      recentPartners:  'Recent Partners',
      pipeline:        'Pipeline',
      recentActivity:  'Recent Activity',
      openPipeline:    'Open pipeline →',
      viewAllActivity: 'View all →',
    },
    partners: {
      title:       'Partners',
      addPartner:  '+ Add Partner',
      searchPlaceholder: 'Search partners…',
      filterTier:  'All Tiers',
      filterStatus:'All Status',
      columns: {
        partner:   'PARTNER',
        tier:      'TIER',
        invested:  'INVESTED',
        pnl:       'P&L',
        entryDate: 'ENTRY DATE',
        status:    'STATUS',
        actions:   '',
      },
      form: {
        title:     'Add Partner',
        editTitle: 'Edit Partner',
        fullName:  'Full Name',
        email:          'Username',
        investedAmount: 'Invested Amount (₹)',
        phone:     'Phone',
        tier:      'Tier',
        entryDate: 'Entry Date',
        notes:     'Notes',
        save:      'Save Partner',
        saving:    'Saving…',
      },
      deleteTitle: 'Delete Partner',
      deleteDesc:  'This will permanently delete the partner and all associated data. This cannot be undone.',
      deleteConfirm: 'Delete Partner',
    },
    partnerDetail: {
      back:        '← Back to Partners',
      edit:        'Edit Partner',
      tabs: {
        overview:     'Overview',
        transactions: 'Transactions',
        pnlReports:   'P&L Reports',
        documents:    'Documents',
        notes:        'Notes',
      },
      addTransaction: '+ Add Transaction',
      addReport:      '+ Add Report',
      addNote:        'Add Note',
      notePlaceholder: 'Internal note…',
      documents: {
        agreement:   'Capital Partnership Agreement',
        security:    'Security / Collateral',
        upload:      'Upload PDF',
        download:    'Download',
        delete:      'Delete',
        empty:       'No document uploaded',
        maxSize:     'PDF only · max 10 MB',
      },
      metrics: {
        invested:    'Invested',
        pnl:         'Current P&L',
        distributed: 'Total Distributed',
        nextPayout:  'Next Payout',
      },
    },
    pipeline: {
      title:    'Pipeline',
      addLead:  '+ Add Lead',
      convert:  'Convert to Partner →',
      daysIn:   'days in stage',
    },
    financials: {
      title:       'Financials',
      aum:         'Total AUM',
      profit:      'Total Profit',
      distributed: 'Total Distributed',
      retained:    'Firm Retained',
      aumGrowth:   'AUM Growth',
      aumByTier:   'AUM by Tier',
      distHistory: 'Distribution History',
      columns: {
        quarter: 'QUARTER',
        year:    'YEAR',
        total:   'TOTAL',
        paid:    'PARTNERS PAID',
        status:  'STATUS',
      },
    },
    distributions: {
      title:   'Distributions',
      steps:   ['Review', 'Confirm', 'Complete'],
      columns: {
        partner: 'PARTNER',
        invested:'INVESTED',
        pnl:     'P&L THIS Q',
        amount:  'DISTRIBUTION',
        status:  'STATUS',
        action:  '',
      },
      markPaid:    'Mark as Paid',
      confirmAll:  'Confirm All →',
      proceed:     'Proceed →',
      summary: {
        total:    'Total Payout',
        partners: 'Partners',
        date:     'Est. Date',
      },
    },
    team: {
      title:       'Team & Permissions',
      auditTitle:  'Audit Log',
      filterAll:   'All Members',
      columns: {
        time:      'TIME',
        action:    'ACTION',
        entity:    'ENTITY',
        by:        'BY',
        details:   'DETAILS',
      },
    },
    pnlEntry: {
      title:         'P&L Entry',
      selectPartner: 'Select partner…',
      month:         'Month',
      year:          'Year',
      total:         'Total Profit',
      forex:         'Forex',
      commodities:   'Commodities',
      crypto:        'Crypto',
      preview:       'Preview',
      save:          'Save Entry',
      saving:        'Saving…',
      history:       'Recent Entries',
    },
    strategies: {
      title:     'Strategies',
      addButton: '+ Add Strategy',
      columns: {
        name:    'NAME',
        market:  'MARKET',
        return:  'AVG RETURN',
        winRate: 'WIN RATE',
        risk:    'RISK',
        status:  'STATUS',
        actions: '',
      },
      form: {
        title:      'Add Strategy',
        editTitle:  'Edit Strategy',
        name:       'Strategy Name',
        market:     'Market',
        status:     'Status',
        monthlyRet: 'Avg Monthly Return (%)',
        winRate:    'Win Rate (%)',
        riskLevel:  'Risk Level',
        notes:      'Notes',
        save:       'Save Strategy',
      },
    },
    allocation: {
      title:         'Asset Allocation',
      selectPartner: 'Select partner…',
      asset:         'Asset Class',
      percent:       'Allocation %',
      amount:        'Amount',
      total:         'Total',
      mustSum:       'Allocations must sum to 100%',
      save:          'Save Allocation',
    },
    users: {
      title:       'User Management',
      addButton:   '+ Create Account',
      columns: {
        name:      'NAME',
        email:     'EMAIL',
        status:    'STATUS',
        lastLogin: 'LAST LOGIN',
        partner:   'LINKED PARTNER',
        actions:   '',
      },
      form: {
        title:       'Create Account',
        email:       'Email Address',
        partner:     'Link to Partner',
        sendInvite:  'Send invite email',
        create:      'Create Account',
        creating:    'Creating…',
      },
      reset:   'Reset Password',
      suspend: 'Suspend',
    },
    documents: {
      title:         'Documents',
      selectPartner: 'Select partner…',
      upload:        'Upload',
      download:      'Download',
      delete:        'Delete',
      dragDrop:      'Drag & drop PDF here, or click to browse',
      maxSize:       'PDF only · max 10 MB',
      agreement:     'Capital Partnership Agreement',
      security:      'Security / Collateral',
    },
    content: {
      title:      'Content',
      addButton:  '+ New Article',
      tabs: {
        articles:  'Articles',
        analytics: 'Analytics',
      },
      columns: {
        title:    'TITLE',
        author:   'AUTHOR',
        category: 'CATEGORY',
        status:   'STATUS',
        date:     'DATE',
        actions:  '',
      },
      editor: {
        newTitle:   'New Article',
        editTitle:  'Edit Article',
        title:      'Article Title',
        author:     'Author',
        category:   'Category',
        status:     'Status',
        body:       'Body (Markdown)',
        preview:    'Preview',
        edit:       'Edit',
        saveDraft:  'Save Draft',
        publish:    'Publish',
        publishing: 'Publishing…',
        saving:     'Saving…',
      },
      analytics: {
        ranges: {
          d7:    'Last 7 days',
          d30:   'Last 30 days',
          d90:   'Last 90 days',
          year:  'This year',
        },
        metrics: {
          totalViews:    'Total Page Views',
          uniqueSessions:'Unique Sessions',
          formSubmits:   'Contact Form Submissions',
          whatsappClicks:'WhatsApp Clicks',
        },
        sections: {
          dailyViews:     'Daily page views',
          topArticles:    'Most read articles',
          trafficSources: 'Traffic sources',
          funnel:         'Visitor to lead funnel',
          allEvents:      'All events',
        },
        articleColumns: {
          title:    'ARTICLE',
          views:    'VIEWS',
          category: 'CATEGORY',
        },
        eventsColumns: {
          eventType: 'EVENT TYPE',
          count:     'COUNT',
          share:     '% OF TOTAL',
        },
        funnel: {
          pageViews:      'Page Views',
          calculator:     'Calculator Used',
          cta:            'CTA Clicked',
          formSubmitted:  'Form Submitted',
          leadsCreated:   'Lead Created',
        },
        empty: {
          title:    'No analytics data yet.',
          subtitle: 'Analytics tracking activates as soon as visitors land on wealthonventures.com.',
          hint:     'Check back after some traffic.',
        },
        emptyArticles: 'No article data yet',
        emptyReferrers:'No traffic data yet',
        emptyEvents:   'No events yet',
        direct:        'Direct',
        other:         'Other',
        vsPrevious:    'vs previous period',
      },
    },
    notifications: {
      title:      'Notifications',
      compose:    'Compose',
      recipient:  'Recipient',
      allPartners:'All Partners',
      type:       'Type',
      subject:    'Subject',
      message:    'Message',
      schedule:   'Schedule send',
      send:       'Send Now',
      sending:    'Sending…',
      sentLog:    'Sent Notifications',
      columns: {
        recipient: 'RECIPIENT',
        message:   'MESSAGE',
        type:      'TYPE',
        sentAt:    'SENT AT',
        opened:    'OPENED',
      },
    },
    system: {
      title:       'System',
      website:     'Website',
      database:    'Database',
      storage:     'Storage',
      auth:        'Auth',
      ok:          'Operational',
      error:       'Error',
      checking:    'Checking…',
      recentLogins:'Recent Logins',
      columns: {
        user:   'USER',
        time:   'TIME',
        ip:     'IP',
      },
    },
    confirm: {
      delete:      'Delete',
      cancel:      'Cancel',
    },
  },
} as const

export const APP_NAME = COMPANY_NAME
